CLAHE:
- defaults: [1, 4]
  limits_list: [1, 100]
  param_name: clip_limit
  type: num_interval
- defaults_list: [8, 8]
  limits_list:
  - [1, 100]
  - [1, 100]
  param_name: tile_grid_size
  subparam_names: [height, width]
  type: several_nums
ChannelShuffle: []
Downscale:
- defaults_list: [0.25, 0.25]
  limits_list: [0.01, 0.99]
  param_name: [scale_min, scale_max]
  type: min_max
- options_list: [0, 1, 2, 3, 4]
  param_name: interpolation
  type: radio
Equalize:
- options_list: [cv, pil]
  param_name: mode
  type: radio
- {defaults: 1, param_name: by_channels, type: checkbox}
HueSaturationValue:
- defaults: [-20, 20]
  limits_list: [-100, 100]
  param_name: hue_shift_limit
  type: num_interval
- defaults: [-30, 30]
  limits_list: [-100, 100]
  param_name: sat_shift_limit
  type: num_interval
- defaults: [-20, 20]
  limits_list: [-100, 100]
  param_name: val_shift_limit
  type: num_interval
ImageCompression:
- options_list: [0, 1]
  param_name: compression_type
  type: radio
- defaults_list: [80, 100]
  limits_list: [0, 100]
  param_name: [quality_lower, quality_upper]
  type: min_max
InvertImg: []
Posterize:
- defaults_list: [4, 4, 4]
  limits_list:
  - [0, 8]
  - [0, 8]
  - [0, 8]
  param_name: num_bits
  subparam_names: [r, g, b]
  type: several_nums
RGBShift:
- defaults: [-20, 20]
  limits_list: [-255, 255]
  param_name: r_shift_limit
  type: num_interval
- defaults: [-20, 20]
  limits_list: [-255, 255]
  param_name: g_shift_limit
  type: num_interval
- defaults: [-20, 20]
  limits_list: [-255, 255]
  param_name: b_shift_limit
  type: num_interval
RandomBrightnessContrast:
- defaults: [-0.2, 0.2]
  limits_list: [-1.0, 1.0]
  param_name: brightness_limit
  type: num_interval
- defaults: [-0.2, 0.2]
  limits_list: [-1.0, 1.0]
  param_name: contrast_limit
  type: num_interval
- {defaults: 1, param_name: brightness_by_max, type: checkbox}
RandomFog:
- defaults_list: [0.1, 0.2]
  limits_list: [0.0, 1.0]
  param_name: [fog_coef_lower, fog_coef_upper]
  type: min_max
- defaults: 0.08
  limits_list: [0.0, 1.0]
  param_name: alpha_coef
  type: num_interval
RandomGamma:
- defaults: [80, 120]
  limits_list: [0, 200]
  param_name: gamma_limit
  type: num_interval
RandomGridShuffle:
- defaults_list: [3, 3]
  limits_list:
  - [1, 10]
  - [1, 10]
  param_name: grid
  subparam_names: [vertical, horizontal]
  type: several_nums
RandomRain:
- defaults_list: [-10, 10]
  limits_list: [-20, 20]
  param_name: [slant_lower, slant_upper]
  type: min_max
- defaults: 20
  limits_list: [0, 100]
  param_name: drop_length
  type: num_interval
- defaults: 1
  limits_list: [1, 5]
  param_name: drop_width
  type: num_interval
- {param_name: drop_color, type: rgb}
- defaults: 7
  limits_list: [1, 15]
  param_name: blur_value
  type: num_interval
- defaults: 0.7
  limits_list: [0.0, 1.0]
  param_name: brightness_coefficient
  type: num_interval
- options_list: [None, drizzle, heavy, torrential]
  param_name: rain_type
  type: radio
RandomSnow:
- defaults_list: [0.1, 0.2]
  limits_list: [0.0, 1.0]
  param_name: [snow_point_lower, snow_point_upper]
  type: min_max
- defaults: 2.5
  limits_list: [0.0, 5.0]
  param_name: brightness_coeff
  type: num_interval
Solarize:
- defaults: 128
  limits_list: [0, 255]
  param_name: threshold
  type: num_interval
ToGray: []
ToSepia: []
RandomToneCurve:
  - defaults: 0.1
    limits_list: [0.0, 1.0]
    param_name: scale
    type: num_interval
FancyPCA:
  - defaults: 0.1
    limits_list: [0.0, 10.0]
    param_name: alpha
    type: num_interval
ColorJitter:
  - defaults: [0.8, 1.2]
    limits_list: [0.01, 10.0]
    param_name: brightness
    type: num_interval
  - defaults: [ 0.8, 1.2 ]
    limits_list: [ 0.01, 10.0 ]
    param_name: contrast
    type: num_interval
  - defaults: [ 0.8, 1.2 ]
    limits_list: [ 0.01, 10.0 ]
    param_name: saturation
    type: num_interval
  - defaults: [ -0.2, 0.2 ]
    limits_list: [ -0.5, 0.5 ]
    param_name: hue
    type: num_interval
Sharpen:
  - defaults: [ 0.2, 0.5 ]
    limits_list: [ 0.0, 1.0 ]
    param_name: alpha
    type: num_interval
  - defaults: [ 0.5, 1.0 ]
    limits_list: [ 0.0, 10.0 ]
    param_name: lightness
    type: num_interval
Emboss:
  - defaults: [ 0.2, 0.5 ]
    limits_list: [ 0.0, 1.0 ]
    param_name: alpha
    type: num_interval
  - defaults: [ 0.2, 0.7 ]
    limits_list: [ 0.0, 10.0 ]
    param_name: strength
    type: num_interval
Superpixels:
  - defaults: 0.1
    limits_list: [ 0.0, 1.0 ]
    param_name: p_replace
    type: num_interval
  - defaults: 100
    limits_list: [ 1, 1000 ]
    param_name: n_segments
    type: num_interval
  - defaults: 128
    limits_list: [ 32, 256 ]
    param_name: max_size
    type: num_interval
  - options_list: [ 0, 1, 2, 3, 4 ]
    param_name: interpolation
    type: radio
RingingOvershoot:
  - defaults: [7, 15]
    limits_list: [ 3, 100 ]
    param_name: blur_limit
    type: num_interval
  - defaults: [ 0.7, 1.57 ]
    limits_list: [ 0.0, 3.14 ]
    param_name: cutoff
    type: num_interval
UnsharpMask:
  - defaults: [ 3, 7 ]
    limits_list: [ 1, 100 ]
    param_name: blur_limit
    step: 2
    type: num_interval
  - defaults: [0.0, 0.0]
    limits_list: [0.0, 100.0]
    param_name: sigma_limit
    type: num_interval
  - defaults: [ 0.2, 0.5 ]
    limits_list: [ 0.0, 1.0 ]
    param_name: alpha
    type: num_interval
  - defaults: 10
    limits_list: [ 0, 255 ]
    param_name: threshold
    type: num_interval
PixelDropout:
  - defaults: 0.01
    limits_list: [ 0.0, 1.0 ]
    param_name: dropout_prob
    type: num_interval
  - options_list: [0, 1]
    param_name: per_channel
    type: radio
  - {param_name: drop_value, type: rgb}
Spatter:
  - defaults: 0.65
    limits_list: [ -10.0, 10.0 ]
    param_name: mean
    type: num_interval
  - defaults: 0.3
    limits_list: [ 0.0, 100.0 ]
    param_name: std
    type: num_interval
  - defaults: 2.0
    limits_list: [ -10.0, 10.0 ]
    param_name: gauss_sigma
    type: num_interval
  - defaults: 0.68
    limits_list: [ -10.0, 10.0 ]
    param_name: cutout_threshold
    type: num_interval
  - defaults: 0.6
    limits_list: [ -10.0, 10.0 ]
    param_name: intensity
    type: num_interval
  - options_list: [ rain, mud ]
    param_name: mode
    type: radio
