ChannelDropout:
    - defaults: [1, 1]
      limits_list: [1, 3]
      param_name: channel_drop_range
      type: num_interval
    - defaults: 0
      limits_list: [0, 255]
      param_name: fill_value
      type: num_interval
CoarseDropout:
  - defaults_list: [8, 8]
    limits_list: [1, 100]
    min_diff: 0
    param_name: [min_holes, max_holes]
    type: min_max
  - defaults_list: [8, 8]
    limits_list: [1, 100]
    min_diff: 0
    param_name: [min_height, max_height]
    type: min_max
  - defaults_list: [8, 8]
    limits_list: [1, 100]
    min_diff: 0
    param_name: [min_width, max_width]
    type: min_max
  - {param_name: fill_value, type: rgb}
