Resize:
  - param_name: height
    placeholder:
      defaults: image_half_height
      limits_list: [1, image_height]
    type: num_interval
  - param_name: width
    placeholder:
      defaults: image_half_width
      limits_list: [1, image_width]
    type: num_interval
  - options_list: [0, 1, 2, 3, 4]
    param_name: interpolation
    type: radio
RandomScale:
  - defaults: [-0.1, 0.1]
    limits_list: [-0.9, 2.0]
    param_name: scale_limit
    type: num_interval
  - options_list: [0, 1, 2, 3, 4]
    param_name: interpolation
    type: radio
LongestMaxSize:
  - defaults: 512
    limits_list: [1, 1024]
    param_name: max_size
    type: num_interval
  - options_list: [0, 1, 2, 3, 4]
    param_name: interpolation
    type: radio
SmallestMaxSize:
  - defaults: 512
    limits_list: [1, 1024]
    param_name: max_size
    type: num_interval
  - options_list: [0, 1, 2, 3, 4]
    param_name: interpolation
    type: radio
Rotate:
  - defaults: [-90, 90]
    limits_list: [-360, 360]
    param_name: limit
    type: num_interval
  - options_list: [0, 1, 2, 3, 4]
    param_name: interpolation
    type: radio
  - options_list: [0, 1, 2, 3, 4]
    param_name: border_mode
    type: radio
  - {param_name: value, type: rgb}
RandomRotate90: []
ShiftScaleRotate:
  - defaults: [-0.06, 0.06]
    limits_list: [-1.0, 1.0]
    param_name: shift_limit
    type: num_interval
  - defaults: [-0.1, 0.1]
    limits_list: [-2.0, 2.0]
    param_name: scale_limit
    type: num_interval
  - defaults: [-90, 90]
    limits_list: [-360, 360]
    param_name: rotate_limit
    type: num_interval
  - options_list: [0, 1, 2, 3, 4]
    param_name: interpolation
    type: radio
  - options_list: [0, 1, 2, 3, 4]
    param_name: border_mode
    type: radio
  - {param_name: value, type: rgb}
ElasticTransform:
  - defaults: 1.0
    limits_list: [0.0, 10.0]
    param_name: alpha
    type: num_interval
  - defaults: 50.0
    limits_list: [0.0, 200.0]
    param_name: sigma
    type: num_interval
  - defaults: 50.0
    limits_list: [0.0, 200.0]
    param_name: alpha_affine
    type: num_interval
  - options_list: [0, 1, 2, 3, 4]
    param_name: interpolation
    type: radio
  - options_list: [0, 1, 2, 3, 4]
    param_name: border_mode
    type: radio
  - {param_name: value, type: rgb}
Flip: []
HorizontalFlip: []
VerticalFlip: []
Transpose: []
OpticalDistortion:
  - defaults: [-0.3, 0.3]
    limits_list: [-2.0, 2.0]
    param_name: distort_limit
    type: num_interval
  - defaults: [-0.05, 0.05]
    limits_list: [-1.0, 1.0]
    param_name: shift_limit
    type: num_interval
  - options_list: [0, 1, 2, 3, 4]
    param_name: interpolation
    type: radio
  - options_list: [0, 1, 2, 3, 4]
    param_name: border_mode
    type: radio
  - {param_name: value, type: rgb}
GridDistortion:
  - defaults: 5
    limits_list: [1, 15]
    param_name: num_steps
    type: num_interval
  - defaults: [-0.3, 0.3]
    limits_list: [-2.0, 2.0]
    param_name: distort_limit
    type: num_interval
  - options_list: [0, 1, 2, 3, 4]
    param_name: interpolation
    type: radio
  - options_list: [0, 1, 2, 3, 4]
    param_name: border_mode
    type: radio
  - {param_name: value, type: rgb}
SafeRotate:
  - defaults: 90
    limits_list: [0, 360]
    param_name: limit
    type: num_interval
  - {param_name: value, type: rgb}
  - options_list: [ 0, 1, 2, 3, 4 ]
    param_name: interpolation
    type: radio
  - options_list: [ 0, 1, 2, 3, 4 ]
    param_name: border_mode
    type: radio
Perspective:
  - defaults: [0.05, 0.1]
    limits_list: [0.0, 2.0]
    param_name: scale
    type: num_interval
  - options_list: [0, 1]
    param_name: keep_size
    type: radio
  - options_list: [ 0, 1, 2, 3, 4 ]
    param_name: pad_mode
    type: radio
  - {param_name: pad_val, type: rgb}
  - options_list: [ 0, 1 ]
    param_name: fit_output
    type: radio
  - options_list: [ 0, 1, 2, 3, 4 ]
    param_name: interpolation
    type: radio
PiecewiseAffine:
  - defaults: [ 0.03, 0.05 ]
    limits_list: [ 0.0, 100.0 ]
    param_name: scale
    type: num_interval
  - defaults: 4
    limits_list: [0, 100]
    param_name: nb_rows
    type: num_interval
  - defaults: 4
    limits_list: [ 0, 100 ]
    param_name: nb_cols
    type: num_interval
  - options_list: [ 0, 1, 2, 3, 4, 5 ]
    param_name: interpolation
    type: radio
  - defaults: 0
    limits_list: [0, 255]
    param_name: cval
    type: num_interval
  - options_list: [constant, edge, symmetric, reflect, wrap]
    param_name: mode
    type: radio
  - options_list: [0, 1]
    param_name: absolute_scale
    type: radio
PadIfNeeded:
  - defaults: 1024
    limits_list: [1, 2048]
    param_name: min_height
    type: num_interval
  - defaults: 1024
    limits_list: [ 1, 2048 ]
    param_name: min_width
    type: num_interval
  - options_list: [center, top_left, top_right, bottom_left, bottom_right, random]
    param_name: position
    type: radio
  - options_list: [ 0, 1, 2, 3, 4 ]
    param_name: border_mode
    type: radio
  - {param_name: value, type: rgb}
