GaussNoise:
  - defaults: [10.0, 50.0]
    limits_list: [0.0, 500.0]
    param_name: var_limit
    type: num_interval
  - defaults: 0.0
    limits_list: [-100.0, 100.0]
    param_name: mean
    type: num_interval
ISONoise:
  - defaults: [0.01, 0.05]
    limits_list: [0.0, 1.0]
    param_name: color_shift
    type: num_interval
  - defaults: [0.1, 0.5]
    limits_list: [0.0, 2.0]
    param_name: intensity
    type: num_interval
MultiplicativeNoise:
  - defaults: [0.9, 1.1]
    limits_list: [0.1, 5.0]
    param_name: multiplier
    type: num_interval
  - {defaults: 1, param_name: per_channel, type: checkbox}
  - {defaults: 1, param_name: elementwise, type: checkbox}
