name: CI

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ "3.12" ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update pip
        run: python -m pip install --upgrade pip
      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
      - name: Install dev requirements
        run: pip install -r requirements_dev.txt
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run tests with pytest
        run:
          pytest
      - name: Run checks code formatting with ruff and mypy
        run: pre-commit run --files $(find src -type f)
